[package]
name = "universal-hot-key"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uhk_input = { path = "uhk_input" }
uhk-scripting = { path = "uhk-scripting" }